name: KQL Tests
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch full history for diff test.
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install kql-tester
      run: |
        pip install -r requirements.txt
    
    - name: Get changed YAML files
      id: changed-files
      run: |
        git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.ya\?ml$' > changed_files.txt || true
        
        if [ -s changed_files.txt ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Run KQL Tests on changed files
      if: steps.changed-files.outputs.has_changes == 'true'
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        LOGS_WORKSPACE_ID: ${{ secrets.LOGS_WORKSPACE_ID }}
      run: | 
        while IFS= read -r file; do
          if [ -f "$file" ]; then
            echo "Testing file: $file"
            python kql-tester.py -d "$file" -tT query-back-search -eE -tF # Does the KQL compile and run? Is the run efficient?
            python kql-tester.py -d "$file" -tT results-diff -tF # Is the changed rule worse than before?
          fi
        done < changed_files.txt

    # First checks that there were results in case of disabled/undeployed rules which are not kql tested.
    - name: Pretty Display KQL Testing Results.
      run: |       
        if [ ! -f test_results/results.yml ]; then
          echo "No results.yml found. Skipping test results formatting."
        else
          echo "Formatting test results... This process will fail if a test FAILed."
          cd .github
          python format-test-results.py
          cat test-results.md >> $GITHUB_STEP_SUMMARY
        fi

    # Store test_results/results.yml as a job artifact (after formatting is done)
    - name: Store Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: test_results
        path: |
          test_results/results.yml
          .github/test-results.md
      continue-on-error: true